site_name: Cyb Netics Docs

site_url: https://example.com
theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
    logo: assets/images/T1_xDrip+logo_white_236x236.png
    logo: assets/images/T1_xDrip+logo_Black_236x236.png
    favicon: assets/images/favicon.png
    palette:
      primary: Black
      scheme: default
    nav_style: primary

nav:
- Home: 'index.md'

- Xdrip :
    - 'Download': 'user-guide/xdrip - Download.md'
    - 'Install': 'user-guide/xdrip/xdrip - install.md'
    - 'Xdrip connection Problem fix': 'user-guide/Xdrip connection Problem fix.md'
    - 'Xdrip Follower Setup': 'user-guide/Xdrip Follower Setup.md'
    - 'Xdrip Setting up Glucose Meters': 'user-guide/Xdrip - Setting up Glucose Meters.md'

- Nightscout :
    - 'Specifications': 'user-guide/Specifications.md'
    - 'Part 1 Setting up Github Account ': 'user-guide/Setting_up_Github_Account_part1.md'
    - 'Part 2 Setting up Heroku Account ': 'user-guide/Setting_up_Heroku_Account_part2.md'
    - 'Part 3 Setting up Atlas Account ': 'user-guide/Setting_up_Atlas_Account_part3.md'
    - 'Part 4 - Fork and Deploy cgm remote monitory': 'user-guide/Fork_and_Deploy_cgm_remote_monitory_part4.md'
    - 'Nightscout usefull Information': 'user-guide/Nightscout_usefull_Information.md'
    - 'Nightscout Update': 'user-guide/Nightscout_update.md'
    - 'Redeploying the repository': 'user-guide/Redeploying your repository.md'
    
       
-   Watches:
    - 'Watches': 'user-guide/Watches.md'
    - 'TicWatch-Pro-3-Side-Load': 'user-guide/TicWatch-Pro-3-side-load---xdrip.md'
    - 'Connecting Garmin 945 to Dexcom G6': 'user-guide/Garmin_Connect_BloodReadings.md'
    
-   Diabetes Links:
    - 'Diabetes helpful web links': 'user-guide/Home.md'

- Update :
    - 'Github - Deleting-your-cgm-remote-monitor  ': 'user-guide/Deleting-your-cgm-remote-monitor.md'
    - 'Nightscout Update': 'user-guide/Nightscout_update.md'
    - 'Diabetes helpful web links': 'user-guide/Home.md'

    - 'About': 'about.md'

