site_name: Cyb Netics Docs 


theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
    logo: assets/images/T1_xDrip+logo_white_236x236.png
    logo: assets/images/T1_xDrip+logo_Blackandwhite_236x236.png
    favicon: assets/images/favicon.png
    palette:
      primary: Black
      scheme: default
    nav_style: primary

nav:
- Home: 'index.md'
- Dexcom :
        - 'Dexcom': 'user-guide/Dexcom/Userguide.md'
- Xdrip :
    - 'Download': 'user-guide/xdrip/xdrip - Download.md'
    - 'Install': 'user-guide/xdrip/xdrip - install.md'
    - 'Connection Problem fix': 'user-guide/Xdrip connection Problem fix.md'
    - 'Follower Setup': 'user-guide/Xdrip Follower Setup.md'
    - 'Setting up Glucose Meters': 'user-guide/xdrip/Xdrip - Setting up Glucose Meters.md'
    - 'Sideload Ticwatch Pro ': 'user-guide/xdrip/TicWatch-Pro-3-side-load---xdrip.md'
    

- Nightscout :
    - 'Specifications': 'user-guide/Specifications.md'
    - 'Part 1 Setting up Github Account ': 'user-guide/Nightscout/Setting_up_Github_Account_part1.md'
    - 'Part 2 Setting up Heroku Account ': 'user-guide/Nightscout/Setting_up_Heroku_Account_part2.md'
    - 'Part 3 Setting up Atlas Account ': 'user-guide/Nightscout/Setting_up_Atlas_Account_part3.md'
    - 'Part 4 - Fork and Deploy cgm remote monitory': 'user-guide/Nightscout/Part 4 - Fork and Deploy cgm remote monitory.md'
    - 'Nightscout Update': 'user-guide/Nightscout/Nightscout_update.md'
    - 'Nightscout usefull Information': 'user-guide/Nightscout_usefull_Information.md'
    - 'Redeploying the repository': 'user-guide/Nightscout/Redeploying your repository.md'
    - 'Compatible Watches': 'user-guide/Nightscout/Compatible Watches.md'
    
       
-   Watches:
    - 'Watches': 'user-guide/Watches.md'
    - 'TicWatch-Pro-3-Side-Load': 'user-guide/TicWatch-Pro-3-side-load---xdrip.md'
    - 'Connecting Garmin 945 to Dexcom G6': 'user-guide/Garmin_Connect_BloodReadings.md'
    - 'Compatible Watches': 'user-guide/Watches/Compatible Watches.md'
    

- Helpful Links : 
    - 'Helpful Links': 'user-guide/Helpful/Helplinks.md'
    - 'Github - Deleting-your-cgm-remote-monitor  ': 'user-guide/Helpful/Deleting-your-cgm-remote-monitor.md' 
    - 'About': 'about.md'

