site_name: Xdrip+ Nightscout Android APS Readmedocs 


theme:
    name: material
    language: en
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.tracking
        - navigation.top
        - search.suggest
        - search.highlight
        - content.code.annotate
    logo: assets/images/T1_xDrip+logo_white_236x236.png
    logo: assets/images/T1_xDrip+logo_Blackandwhite_236x236.png
    favicon: assets/images/favicon.png
    palette:
      primary: Black
      scheme: default
    nav_style: primary

extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

nav:
- Home: 'index.md'
- Dexcom :
        - 'Dexcom G6': 'user-guide/Dexcom/Userguide.md'
- Xdrip :
    - 'Download': 'user-guide/xdrip/xdrip - Download.md'
    - 'Install': 'user-guide/xdrip/xdrip - install.md'
    - 'xdrip± Settings': 'user-guide/xdrip/settings.md'
    - 'xdrip± Hamburger Menu': 'user-guide/xdrip/xdrip-HamburgerMenu.md'
    - 'xdrip± Copy Settings': 'user-guide/xdrip/Copy-settings.md'
    - 'Base URL': 'user-guide/xdrip/xdrip - Base.md'
    - 'Compatible - Watches': 'user-guide/xdrip/Compatible Watches.md'
    - 'xdrip± Follower': 'user-guide/xdrip/Xdrip Follower Setup.md'
    - 'Hardware Data Source': 'user-guide/xdrip/xdrip - hardwaredatasource.md'
    - 'G6 & One': 'user-guide/xdrip/xdrip - Dexcom G6 and Dexcom One.md'
    - 'System Status': 'user-guide/xdrip/xdrip - System Status.md'
    - 'Start Sensor': 'user-guide/xdrip/xdrip - Start Sensor.md'
    - 'Connection Problem fix': 'user-guide/Xdrip connection Problem fix.md'
    
    - 'Setting up Glucose Meters': 'user-guide/xdrip/Xdrip - Setting up Glucose Meters.md'
    - 'Sideload Ticwatch Pro ': 'user-guide/xdrip/TicWatch-Pro-3-side-load---xdrip.md'
    

- Nightscout :
    - 'Specifications': 'user-guide/Specifications.md'
    - 'Part 1 Setting up Github Account ': 'user-guide/Nightscout/Setting_up_Github_Account_part1.md'
    - 'Part 2 Setting up Heroku Account ': 'user-guide/Nightscout/Setting_up_Heroku_Account_part2.md'
    - 'Part 3 Setting up Atlas Account ': 'user-guide/Nightscout/Setting_up_Atlas_Account_part3.md'
    - 'Part 4 - Fork and Deploy cgm remote monitory': 'user-guide/Nightscout/Part 4 - Fork and Deploy cgm remote monitory.md'
    - 'Updating Nightscout': 'user-guide/Nightscout/Nightscout_update.md'
    - 'Nightscout usefull Information': 'user-guide/Nightscout/Nightscout_usefull_Information.md'
    - 'Heroku Redeploy Update ': 'user-guide/Nightscout/Redeploying your repository.md'
    - 'Google Cloud Server Setup': 'user-guide/Nightscout/Google Cloud_setup.md'
    - 'Fly_io Server Setup': 'user-guide/Nightscout/Fly_io-setup.md'
    
    - 'Oracle Cloud Setup': 'user-guide/Nightscout/Nightscout_Oracle Cloud - setup.md'
    
       
-   Watches:
    - 'Watches': 'user-guide/Watches.md'
    - 'Sideload Ticwatch Pro': 'user-guide/Watches/TicWatch-Pro-3-side-load---xdrip.md'
    - 'Connecting Garmin 945 to Dexcom G6': 'user-guide/Garmin_Connect_BloodReadings.md'
    - 'Compatible Watches': 'user-guide/Watches/Compatible Watches.md'
    
-   Freestyle Libre : 
    - 'Setup Freestyle Libre 2': 'user-guide/FreestyleLibre/How_to_setup_FreeStyle_Libre_2.md'

- Helpful Links : 
    - 'Helpful Links': 'user-guide/Helpful/Helplinks.md'
    - 'Github - Deleting-your-cgm-remote-monitor  ': 'user-guide/Helpful/Deleting-your-cgm-remote-monitor.md' 
    - 'About': 'about.md'

